spring:
  application:
    name: spring-docker-runtarget
  profiles:
    active: night
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  sql:
    init:
      mode: always

---
spring:
  config:
    activate:
      on-profile: day
greeting: good morning

---
spring:
  config:
    activate:
      on-profile: night
greeting: good evening
