Drop table if exists persons;
CREATE TABLE IF NOT EXISTS persons (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email VARCHAR(100),
    first_name VARCHAR(50),
    last_name VARCHAR(50),
    age int
);



